# AdvanceKillMoney
# Plugin By DeadBush
# https://github.com/deadbushmc

# Write the names of world to enable kill money on
worlds: ["world1", "world2", "world3"]

# if you keep it as "deactivate" then the victim won't loose the money on death but only killer will get the money
# if you keep it "activate" then the victim will loose certain amount of money on death and will be given to the killer
reduceMoney: "activate"

# choose if the the money should be random or custom
# keep it as "activate" to make it custom or keep it as "deactivate" to make it fully random 1-100%
custom: "activate"

# if you have kept custom as on then edit the values how much percentage max should be deducted from victim and given to killer no need to add % at end just add the numeric value
# if you have kept custom as off then ignore it
randomise: 40 # means the killer will get 1-40% money from the victim's account
